pub mod buildinfo;
pub mod callsites;
pub mod capabilities;
pub mod dataview;
pub mod dataxref;
pub mod diff;
pub mod dispatch;
pub mod error;
pub mod export;
pub mod fingerprint;
pub mod funcsig;
pub mod garble;
pub mod gobin;
pub mod goroutines;
pub mod inline;
pub mod itabs;
pub mod moduledata;
pub mod output;
pub mod pclntab;
pub mod plugin;
pub mod probe;
pub mod rewrite;
pub mod stdlib;
pub mod strings;
pub mod types;
pub mod xrefs;

pub use buildinfo::{BuildInfo, Module};
pub use error::Error;
pub use fingerprint::Fingerprint;
pub use gobin::{Container, GoBinary, Section, SectionKind};
pub use itabs::Itab;
pub use moduledata::{ModuleData, SliceHeader};
pub use pclntab::{Function, Pclntab};
pub use probe::{probe, ContainerProbe, SectionInfo};
pub use types::{KindName, Type};

pub type Result<T> = std::result::Result<T, Error>;
